// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7v-6rYL_eidhXW4kF7eNqzktPdzz3X5E',
    appId: '1:282636586043:web:0d8c0fb69703a4de0f201e',
    messagingSenderId: '282636586043',
    projectId: 'envirowatch-e406b',
    authDomain: 'envirowatch-e406b.firebaseapp.com',
    databaseURL: 'https://envirowatch-e406b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'envirowatch-e406b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFVnuhAoYmXP8dtYyhJVcAS761oKWEnH0',
    appId: '1:282636586043:android:39507e8dbb5d97c40f201e',
    messagingSenderId: '282636586043',
    projectId: 'envirowatch-e406b',
    databaseURL: 'https://envirowatch-e406b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'envirowatch-e406b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxQ4LvTrOaT4-Llt3O2lv1jRuQcsky2xU',
    appId: '1:282636586043:ios:7745d767ca00d5e30f201e',
    messagingSenderId: '282636586043',
    projectId: 'envirowatch-e406b',
    databaseURL: 'https://envirowatch-e406b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'envirowatch-e406b.appspot.com',
    iosBundleId: 'com.example.enviroWatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxQ4LvTrOaT4-Llt3O2lv1jRuQcsky2xU',
    appId: '1:282636586043:ios:7745d767ca00d5e30f201e',
    messagingSenderId: '282636586043',
    projectId: 'envirowatch-e406b',
    databaseURL: 'https://envirowatch-e406b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'envirowatch-e406b.appspot.com',
    iosBundleId: 'com.example.enviroWatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7v-6rYL_eidhXW4kF7eNqzktPdzz3X5E',
    appId: '1:282636586043:web:f65701fdfbd9b05c0f201e',
    messagingSenderId: '282636586043',
    projectId: 'envirowatch-e406b',
    authDomain: 'envirowatch-e406b.firebaseapp.com',
    databaseURL: 'https://envirowatch-e406b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'envirowatch-e406b.appspot.com',
  );
}
